site_name: Service Mesh Comparison

nav:
  - Home:
      - Welcome: index.md
      - Sources: sources.md
  - Setup:
      - Environment: environment.md
      - Prerequisites: prerequisites.md
      - Clusters: clusters.md
      - Benchmarking: benchmarks.md

theme:
  name: material

  features:
  - navigation.expand
  - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
