#!/usr/bin/bash
echo ===== FORWARD GRAFANA =====
echo - reporting only errors

kubectl port-forward deployment/kube-prometheus-stack-grafana -n monitoring 3000 > /dev/null

echo ===== SESSION ENDED =====
