alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: true 
prometheus:
  prometheusSpec:
    retention: 60d
grafana:
  imageRenderer:
    enabled: true
hostNetwork: true
